server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/viboot?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Passw0rd

mybatis:
  type-aliases-package: indi.viyoung.viboot.indi.viyoung.viboot.mybatis.entity